// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clientCmd

import "strconv"

type ClientCmd int8

const (
	ClientCmdDEFAULT ClientCmd = 0
)

var EnumNamesClientCmd = map[ClientCmd]string{
	ClientCmdDEFAULT: "DEFAULT",
}

var EnumValuesClientCmd = map[string]ClientCmd{
	"DEFAULT": ClientCmdDEFAULT,
}

func (v ClientCmd) String() string {
	if s, ok := EnumNamesClientCmd[v]; ok {
		return s
	}
	return "ClientCmd(" + strconv.FormatInt(int64(v), 10) + ")"
}
