// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clientCmd

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClientEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsClientEvent(buf []byte, offset flatbuffers.UOffsetT) *ClientEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClientEvent{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsClientEvent(buf []byte, offset flatbuffers.UOffsetT) *ClientEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ClientEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ClientEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClientEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ClientEvent) Event() ClientCmd {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ClientCmd(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ClientEvent) MutateEvent(n ClientCmd) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func ClientEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ClientEventAddEvent(builder *flatbuffers.Builder, Event ClientCmd) {
	builder.PrependInt8Slot(0, int8(Event), 0)
}
func ClientEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
